# Generated by Django 5.1.1 on 2024-12-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_address_first_name_address_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
